### ISSUE TITLE
Logical Flows need last updated by/at

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#1480]

**Comment by kamransaleem** [comment]
Error on running Liquibase:

`Unexpected error running Liquibase: ALTER TABLE only allows columns to be added that can contain nulls, or have a DEFAULT definition specified, or the column being added is an identity or timestamp column, or alternatively if none of the previous conditions are satisfied the table must be empty to allow addition of this column. Column 'last_updated_at' cannot be added to non-empty table 'logical_flow' because it does not satisfy these conditions. [Failed SQL: ALTER TABLE [logical_flow] ADD [last_updated_at] [datetime] NOT NULL]`

Will fix as part of this issue.
