### ISSUE TITLE
Importing Data

### ISSUE THREAD

**Issue by quintona** [khartec/waltz#3492]
I am just starting to play with waltz. I have a local instance running and I am just trying to figure out how to import data. So far the only logical entry point I can find is the sample jobs, e.g:  ```com.khartec.waltz.jobs.sample.AppGenerator```

My next step was to create my own custom job to pull data from my existing data sources and populate. Is this the best/intended approach or have I missed something obvious in the process?

**Comment by quintona** [comment]
So, update here: I have managed to get data imported into Waltz. I create the org hierarchy, and then ran the app generator, just using the dummy data that is included in the ```waltz-jobs``` samples. 

It took quite some messing with the POM file in of ```waltz-jobs``` to get rid of all the ```ClassNotFound``` exceptions. I am assuming there is something in my local environment or the way I am going about this that is causing problems here? In any event, my intention would be to simply create a seperate import project that creates dependencies against a stable release (until I am more across this code base)  

I then get some unexpected behaviour in that I can see application counts in the org hierarchy.
<img width="394" alt="screen shot 2018-10-17 at 11 09 21 pm" src="https://user-images.githubusercontent.com/2283541/47085353-18d46200-d262-11e8-9d9d-479dd0581c24.png">

However when I select the org there aren't any applications in the org view:
<img width="414" alt="screen shot 2018-10-17 at 11 09 34 pm" src="https://user-images.githubusercontent.com/2283541/47085374-2a1d6e80-d262-11e8-8c71-23374df6e0e3.png">

My Assumption here is that there is a broken relationship in the underlying data, however I have read the docs and played with generating other data, but I can't seem to get rid of the issue. Any advise on order and how to get started with the data important and management aspects?

**Comment by davidwatkins73** [comment]
Hi Quinton,
The `waltz-jobs` sub project should compile fine.  However your approach sounds sensible and is similar to what we do at DB.  We have a separate project full of data loaders controlled by a quartz scheduler.  They import apps on a periodic basis, tracking via the `asset-code` field (heads up - this may be renamed `external-id` in a subsequent release to bring it in line with the other entities).  

The problem with not seeing any apps is because the hierarchy of org-units needs to be built.  You can do this via the admin screen:

![image](https://user-images.githubusercontent.com/576829/47086563-c8cdaf00-d211-11e8-8721-1c547f5bccdf.png)

then:

![image](https://user-images.githubusercontent.com/576829/47086645-fdda0180-d211-11e8-9975-5ad2a134080f.png)

This populates the `entity_hierarchy` table, which is how we can quickly determine what apps fall under a given org unit.

**Comment by quintona** [comment]
Thanks @davidwatkins73 I have verified that this works. I have created a separate project to import my custom data from upstream sources, using kotlin and gradle (overdue to learn a new language). 

At this stage your jars aren't available in a maven repo, so I have built them locally, however I have had trouble declaring dependencies on them because of the profiles in the POMs. As a work around I have simply hacked the POM files, rebuilt and installed in my maven repo. This is obviously not sustainable, and I will need to come back and find a better solution. 

My next steps are to get some feedback on the tool, now that it has some data. If I am starting to get some real interest then I will take the time fix the dependency issue and also publish an example import project so that other users can benefit. 

Thanks again
